### ISSUE TITLE
회원-신고 프로세스 상의 논의점 : 신고 게시판 신설

### ISSUE THREAD

**Issue by hohojeong091** [himedi3DHS/TN-project#27]
# 이슈제목
### 개요

신고 목록 게시판을 만들다 보니... 
신고 목록에 추가 되는 신고 건들은 회원이 특정 게시물이나 댓글을 보고 "신고"버튼을 눌렀을 때 목록에 추가 된다 
정도로만 생각을 했었는데~~

신고 내역을 작성하는 공간이 있고, 컬럼 또한 존재하기 때문에 
신고 내역을 상세히 작성하는 게시판이 존재할 것 같다는 판단이 들었습니다. 

혹쉬, 다른 분들 생각은 어떤지 궁금하네요~~

**Comment by MIdWit0828** [comment]
게시판보단 팝업으로 띄워서 작성하게 하는 게 좋지 않을까요?
유저가 신고를 할때 실질적으로 작성하는 항목이
1. 신고 카테고리 설정
2. 상세 내용 
정도라서 따로 신고용 개시판을 만들지는 않는게 좋겠습니다

**Comment by chk2023** [comment]
댓글 신고-> 팝업이 떠서 옵션 박스에서 광고, 비방, 기타 중 선택
기타 선택-> 신고 내용을 작성

댓글은 일단 이렇게 구상했습니다.

**Comment by hohojeong091** [comment]
확인했습니당~~

**Comment by MIdWit0828** [comment]
결론 공지해주시고 이슈 닫아주세요~

**Comment by hohojeong091** [comment]
일단 개발 해보면서 더 적합한 방향으로 만들어 보도록 하겠습니다 !
