### ISSUE TITLE
05 레이아웃 작성

### ISSUE THREAD

**Issue by chk2023** [himedi3DHS/TN-project#3]
# 05 레이아웃 작성
### 개요
- [뷰 레이아웃을 위한 사전 레이아웃 제작]
- [블로그 형태의 조회 페이지를 보여준다]
### 상세정보
- 대분류 : [레이아웃]
- 중분류 : [레이아웃]
- 소분류 : [조회2]
- 구분 : [블로그]
- 패키지 : [/templates/layout]
- output : [html]
- view : [ template/layout/layout0-4.html ]

**Comment by MIdWit0828** [comment]
병합완료
