### ISSUE TITLE
화면설계/commonCSS 작성(front)

### ISSUE THREAD

**Issue by ddalla0425** [himedi3DHS/TN-project#4]
# html,css : layout 병합 및 common CSS 분리
### 개요
- [뷰 레이아웃을 위한 사전 레이아웃 제작]
- [5명의 팀원이 사전 레이아웃 5개를 나눠 작업]
- [5개의 사전 레이아웃 파일을  뷰 레이아웃 파일로 병합 및 수정]
### 상세정보
- 대분류 : [레이아웃 작성]
- 중분류 : [레이아웃 병합]
- 소분류 : [레이아웃 병합 ]
- 구분 : [블로그]
- output : [html]
- view : [ template/layout/view_layout.html ]
### 코드 흐름
[ html : 01_layout.html 부터 05_layout.html의 태그 구조 및 클래스명 수정 및 통합 
 css : 01_layout.css 부터 05_layout.css의 중복 css 통합 및 수정 ]

**Comment by MIdWit0828** [comment]
완성
