### ISSUE TITLE
02 레이아웃 작성

### ISSUE THREAD

**Issue by syyyl** [himedi3DHS/TN-project#6]
### 개요
- [해당 이슈가 어떠한 이유로 발생했는지 기술]
- [해당 이슈가 어떤 기능을 하는지 기술]
### 상세정보
- 대분류 : [레이아웃 작성]
- 중분류 : [레이아웃 작성]
- 소분류 : [레이아웃 작성]
- 구분 : [블로그]
- output : [html]
- view : [ template/layout/form_layout.html ]
### 코드 흐름
[ 로그인 폼 그룹 작성, 드롭다운 메뉴 작성,  검색 창 작성, 라디오버튼 및 체크박스, 버튼 작성, 각 요소에 해당하는 css 작성 ]
[ 드롭다운 메뉴에서 옵션 부분 css 제외, 버튼 css 색상과 크기 별도의 클래스로 분류 ]

**Comment by MIdWit0828** [comment]
병합완료
